//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.7
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from /Users/ikeough/Documents/IFC-gen/schemas/STEP.g4 by ANTLR 4.7

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

namespace STEP {
using System;
using System.IO;
using System.Text;
using System.Diagnostics;
using System.Collections.Generic;
using Antlr4.Runtime;
using Antlr4.Runtime.Atn;
using Antlr4.Runtime.Misc;
using Antlr4.Runtime.Tree;
using DFA = Antlr4.Runtime.Dfa.DFA;

[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.7")]
[System.CLSCompliant(false)]
public partial class STEPParser : Parser {
	protected static DFA[] decisionToDFA;
	protected static PredictionContextCache sharedContextCache = new PredictionContextCache();
	public const int
		T__0=1, T__1=2, T__2=3, T__3=4, T__4=5, T__5=6, T__6=7, T__7=8, IntegerLiteral=9, 
		Letter=10, CapitalLetter=11, DateTime=12, PlusMinus=13, Derived=14, BoolLogical=15, 
		Enum=16, RealLiteral=17, DATA=18, ENDSEC=19, FILE_DESCRIPTION=20, FILE_NAME=21, 
		FILE_SCHEMA=22, HEADER=23, Id=24, ISO=25, ISO_END=26, StringLiteral=27, 
		TypeRef=28, Undefined=29, AnyString=30, NewlineChar=31, WS=32, Comments=33;
	public const int
		RULE_author = 0, RULE_authorisation = 1, RULE_collection = 2, RULE_collectionValue = 3, 
		RULE_constructor = 4, RULE_data = 5, RULE_description = 6, RULE_file = 7, 
		RULE_fileDescription = 8, RULE_fileName = 9, RULE_filePath = 10, RULE_fileSchema = 11, 
		RULE_header = 12, RULE_implementation = 13, RULE_instance = 14, RULE_name = 15, 
		RULE_originating_system = 16, RULE_organization = 17, RULE_parameter = 18, 
		RULE_preprocessor_version = 19, RULE_timeStamp = 20;
	public static readonly string[] ruleNames = {
		"author", "authorisation", "collection", "collectionValue", "constructor", 
		"data", "description", "file", "fileDescription", "fileName", "filePath", 
		"fileSchema", "header", "implementation", "instance", "name", "originating_system", 
		"organization", "parameter", "preprocessor_version", "timeStamp"
	};

	private static readonly string[] _LiteralNames = {
		null, "'('", "','", "')'", "'()'", "';'", "'''", "'.'", "'='", null, null, 
		null, null, null, "'*'", null, null, null, "'DATA'", "'ENDSEC'", "'FILE_DESCRIPTION'", 
		"'FILE_NAME'", "'FILE_SCHEMA'", "'HEADER'", null, null, null, null, null, 
		"'$'"
	};
	private static readonly string[] _SymbolicNames = {
		null, null, null, null, null, null, null, null, null, "IntegerLiteral", 
		"Letter", "CapitalLetter", "DateTime", "PlusMinus", "Derived", "BoolLogical", 
		"Enum", "RealLiteral", "DATA", "ENDSEC", "FILE_DESCRIPTION", "FILE_NAME", 
		"FILE_SCHEMA", "HEADER", "Id", "ISO", "ISO_END", "StringLiteral", "TypeRef", 
		"Undefined", "AnyString", "NewlineChar", "WS", "Comments"
	};
	public static readonly IVocabulary DefaultVocabulary = new Vocabulary(_LiteralNames, _SymbolicNames);

	[NotNull]
	public override IVocabulary Vocabulary
	{
		get
		{
			return DefaultVocabulary;
		}
	}

	public override string GrammarFileName { get { return "STEP.g4"; } }

	public override string[] RuleNames { get { return ruleNames; } }

	public override string SerializedAtn { get { return new string(_serializedATN); } }

	static STEPParser() {
		decisionToDFA = new DFA[_ATN.NumberOfDecisions];
		for (int i = 0; i < _ATN.NumberOfDecisions; i++) {
			decisionToDFA[i] = new DFA(_ATN.GetDecisionState(i), i);
		}
	}

		public STEPParser(ITokenStream input) : this(input, Console.Out, Console.Error) { }

		public STEPParser(ITokenStream input, TextWriter output, TextWriter errorOutput)
		: base(input, output, errorOutput)
	{
		Interpreter = new ParserATNSimulator(this, _ATN, decisionToDFA, sharedContextCache);
	}
	public partial class AuthorContext : ParserRuleContext {
		public ITerminalNode AnyString() { return GetToken(STEPParser.AnyString, 0); }
		public AuthorContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_author; } }
		public override void EnterRule(IParseTreeListener listener) {
			ISTEPListener typedListener = listener as ISTEPListener;
			if (typedListener != null) typedListener.EnterAuthor(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			ISTEPListener typedListener = listener as ISTEPListener;
			if (typedListener != null) typedListener.ExitAuthor(this);
		}
	}

	[RuleVersion(0)]
	public AuthorContext author() {
		AuthorContext _localctx = new AuthorContext(Context, State);
		EnterRule(_localctx, 0, RULE_author);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 42; Match(AnyString);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class AuthorisationContext : ParserRuleContext {
		public ITerminalNode AnyString() { return GetToken(STEPParser.AnyString, 0); }
		public AuthorisationContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_authorisation; } }
		public override void EnterRule(IParseTreeListener listener) {
			ISTEPListener typedListener = listener as ISTEPListener;
			if (typedListener != null) typedListener.EnterAuthorisation(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			ISTEPListener typedListener = listener as ISTEPListener;
			if (typedListener != null) typedListener.ExitAuthorisation(this);
		}
	}

	[RuleVersion(0)]
	public AuthorisationContext authorisation() {
		AuthorisationContext _localctx = new AuthorisationContext(Context, State);
		EnterRule(_localctx, 2, RULE_authorisation);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 44; Match(AnyString);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class CollectionContext : ParserRuleContext {
		public CollectionValueContext[] collectionValue() {
			return GetRuleContexts<CollectionValueContext>();
		}
		public CollectionValueContext collectionValue(int i) {
			return GetRuleContext<CollectionValueContext>(i);
		}
		public CollectionContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_collection; } }
		public override void EnterRule(IParseTreeListener listener) {
			ISTEPListener typedListener = listener as ISTEPListener;
			if (typedListener != null) typedListener.EnterCollection(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			ISTEPListener typedListener = listener as ISTEPListener;
			if (typedListener != null) typedListener.ExitCollection(this);
		}
	}

	[RuleVersion(0)]
	public CollectionContext collection() {
		CollectionContext _localctx = new CollectionContext(Context, State);
		EnterRule(_localctx, 4, RULE_collection);
		int _la;
		try {
			State = 58;
			ErrorHandler.Sync(this);
			switch (TokenStream.LA(1)) {
			case T__0:
				EnterOuterAlt(_localctx, 1);
				{
				State = 46; Match(T__0);
				State = 47; collectionValue();
				State = 52;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
				while (_la==T__1) {
					{
					{
					State = 48; Match(T__1);
					State = 49; collectionValue();
					}
					}
					State = 54;
					ErrorHandler.Sync(this);
					_la = TokenStream.LA(1);
				}
				State = 55; Match(T__2);
				}
				break;
			case T__3:
				EnterOuterAlt(_localctx, 2);
				{
				State = 57; Match(T__3);
				}
				break;
			default:
				throw new NoViableAltException(this);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class CollectionValueContext : ParserRuleContext {
		public ITerminalNode RealLiteral() { return GetToken(STEPParser.RealLiteral, 0); }
		public ITerminalNode IntegerLiteral() { return GetToken(STEPParser.IntegerLiteral, 0); }
		public ITerminalNode StringLiteral() { return GetToken(STEPParser.StringLiteral, 0); }
		public ITerminalNode AnyString() { return GetToken(STEPParser.AnyString, 0); }
		public ITerminalNode Id() { return GetToken(STEPParser.Id, 0); }
		public ConstructorContext constructor() {
			return GetRuleContext<ConstructorContext>(0);
		}
		public ITerminalNode Undefined() { return GetToken(STEPParser.Undefined, 0); }
		public CollectionValueContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_collectionValue; } }
		public override void EnterRule(IParseTreeListener listener) {
			ISTEPListener typedListener = listener as ISTEPListener;
			if (typedListener != null) typedListener.EnterCollectionValue(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			ISTEPListener typedListener = listener as ISTEPListener;
			if (typedListener != null) typedListener.ExitCollectionValue(this);
		}
	}

	[RuleVersion(0)]
	public CollectionValueContext collectionValue() {
		CollectionValueContext _localctx = new CollectionValueContext(Context, State);
		EnterRule(_localctx, 6, RULE_collectionValue);
		try {
			State = 67;
			ErrorHandler.Sync(this);
			switch (TokenStream.LA(1)) {
			case RealLiteral:
				EnterOuterAlt(_localctx, 1);
				{
				State = 60; Match(RealLiteral);
				}
				break;
			case IntegerLiteral:
				EnterOuterAlt(_localctx, 2);
				{
				State = 61; Match(IntegerLiteral);
				}
				break;
			case StringLiteral:
				EnterOuterAlt(_localctx, 3);
				{
				State = 62; Match(StringLiteral);
				}
				break;
			case AnyString:
				EnterOuterAlt(_localctx, 4);
				{
				State = 63; Match(AnyString);
				}
				break;
			case Id:
				EnterOuterAlt(_localctx, 5);
				{
				State = 64; Match(Id);
				}
				break;
			case TypeRef:
				EnterOuterAlt(_localctx, 6);
				{
				State = 65; constructor();
				}
				break;
			case Undefined:
				EnterOuterAlt(_localctx, 7);
				{
				State = 66; Match(Undefined);
				}
				break;
			default:
				throw new NoViableAltException(this);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class ConstructorContext : ParserRuleContext {
		public ITerminalNode TypeRef() { return GetToken(STEPParser.TypeRef, 0); }
		public ParameterContext[] parameter() {
			return GetRuleContexts<ParameterContext>();
		}
		public ParameterContext parameter(int i) {
			return GetRuleContext<ParameterContext>(i);
		}
		public ConstructorContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_constructor; } }
		public override void EnterRule(IParseTreeListener listener) {
			ISTEPListener typedListener = listener as ISTEPListener;
			if (typedListener != null) typedListener.EnterConstructor(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			ISTEPListener typedListener = listener as ISTEPListener;
			if (typedListener != null) typedListener.ExitConstructor(this);
		}
	}

	[RuleVersion(0)]
	public ConstructorContext constructor() {
		ConstructorContext _localctx = new ConstructorContext(Context, State);
		EnterRule(_localctx, 8, RULE_constructor);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 69; Match(TypeRef);
			State = 70; Match(T__0);
			State = 72;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			if ((((_la) & ~0x3f) == 0 && ((1L << _la) & ((1L << T__0) | (1L << T__3) | (1L << IntegerLiteral) | (1L << Derived) | (1L << BoolLogical) | (1L << Enum) | (1L << RealLiteral) | (1L << Id) | (1L << StringLiteral) | (1L << TypeRef) | (1L << Undefined) | (1L << AnyString))) != 0)) {
				{
				State = 71; parameter();
				}
			}

			State = 78;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			while (_la==T__1) {
				{
				{
				State = 74; Match(T__1);
				State = 75; parameter();
				}
				}
				State = 80;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
			}
			State = 81; Match(T__2);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class DataContext : ParserRuleContext {
		public ITerminalNode DATA() { return GetToken(STEPParser.DATA, 0); }
		public ITerminalNode ENDSEC() { return GetToken(STEPParser.ENDSEC, 0); }
		public InstanceContext[] instance() {
			return GetRuleContexts<InstanceContext>();
		}
		public InstanceContext instance(int i) {
			return GetRuleContext<InstanceContext>(i);
		}
		public DataContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_data; } }
		public override void EnterRule(IParseTreeListener listener) {
			ISTEPListener typedListener = listener as ISTEPListener;
			if (typedListener != null) typedListener.EnterData(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			ISTEPListener typedListener = listener as ISTEPListener;
			if (typedListener != null) typedListener.ExitData(this);
		}
	}

	[RuleVersion(0)]
	public DataContext data() {
		DataContext _localctx = new DataContext(Context, State);
		EnterRule(_localctx, 10, RULE_data);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 83; Match(DATA);
			State = 84; Match(T__4);
			State = 88;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			while (_la==Id) {
				{
				{
				State = 85; instance();
				}
				}
				State = 90;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
			}
			State = 91; Match(ENDSEC);
			State = 92; Match(T__4);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class DescriptionContext : ParserRuleContext {
		public ITerminalNode AnyString() { return GetToken(STEPParser.AnyString, 0); }
		public CollectionContext collection() {
			return GetRuleContext<CollectionContext>(0);
		}
		public DescriptionContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_description; } }
		public override void EnterRule(IParseTreeListener listener) {
			ISTEPListener typedListener = listener as ISTEPListener;
			if (typedListener != null) typedListener.EnterDescription(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			ISTEPListener typedListener = listener as ISTEPListener;
			if (typedListener != null) typedListener.ExitDescription(this);
		}
	}

	[RuleVersion(0)]
	public DescriptionContext description() {
		DescriptionContext _localctx = new DescriptionContext(Context, State);
		EnterRule(_localctx, 12, RULE_description);
		try {
			State = 96;
			ErrorHandler.Sync(this);
			switch (TokenStream.LA(1)) {
			case AnyString:
				EnterOuterAlt(_localctx, 1);
				{
				State = 94; Match(AnyString);
				}
				break;
			case T__0:
			case T__3:
				EnterOuterAlt(_localctx, 2);
				{
				State = 95; collection();
				}
				break;
			default:
				throw new NoViableAltException(this);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class FileContext : ParserRuleContext {
		public ITerminalNode ISO() { return GetToken(STEPParser.ISO, 0); }
		public HeaderContext header() {
			return GetRuleContext<HeaderContext>(0);
		}
		public DataContext data() {
			return GetRuleContext<DataContext>(0);
		}
		public ITerminalNode ISO_END() { return GetToken(STEPParser.ISO_END, 0); }
		public FileContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_file; } }
		public override void EnterRule(IParseTreeListener listener) {
			ISTEPListener typedListener = listener as ISTEPListener;
			if (typedListener != null) typedListener.EnterFile(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			ISTEPListener typedListener = listener as ISTEPListener;
			if (typedListener != null) typedListener.ExitFile(this);
		}
	}

	[RuleVersion(0)]
	public FileContext file() {
		FileContext _localctx = new FileContext(Context, State);
		EnterRule(_localctx, 14, RULE_file);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 98; Match(ISO);
			State = 99; header();
			State = 100; data();
			State = 101; Match(ISO_END);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class FileDescriptionContext : ParserRuleContext {
		public ITerminalNode FILE_DESCRIPTION() { return GetToken(STEPParser.FILE_DESCRIPTION, 0); }
		public DescriptionContext description() {
			return GetRuleContext<DescriptionContext>(0);
		}
		public ImplementationContext implementation() {
			return GetRuleContext<ImplementationContext>(0);
		}
		public FileDescriptionContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_fileDescription; } }
		public override void EnterRule(IParseTreeListener listener) {
			ISTEPListener typedListener = listener as ISTEPListener;
			if (typedListener != null) typedListener.EnterFileDescription(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			ISTEPListener typedListener = listener as ISTEPListener;
			if (typedListener != null) typedListener.ExitFileDescription(this);
		}
	}

	[RuleVersion(0)]
	public FileDescriptionContext fileDescription() {
		FileDescriptionContext _localctx = new FileDescriptionContext(Context, State);
		EnterRule(_localctx, 16, RULE_fileDescription);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 103; Match(FILE_DESCRIPTION);
			State = 104; Match(T__0);
			State = 105; description();
			State = 106; Match(T__1);
			State = 107; implementation();
			State = 108; Match(T__2);
			State = 109; Match(T__4);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class FileNameContext : ParserRuleContext {
		public ITerminalNode FILE_NAME() { return GetToken(STEPParser.FILE_NAME, 0); }
		public NameContext name() {
			return GetRuleContext<NameContext>(0);
		}
		public TimeStampContext timeStamp() {
			return GetRuleContext<TimeStampContext>(0);
		}
		public Preprocessor_versionContext preprocessor_version() {
			return GetRuleContext<Preprocessor_versionContext>(0);
		}
		public Originating_systemContext originating_system() {
			return GetRuleContext<Originating_systemContext>(0);
		}
		public AuthorisationContext authorisation() {
			return GetRuleContext<AuthorisationContext>(0);
		}
		public AuthorContext author() {
			return GetRuleContext<AuthorContext>(0);
		}
		public CollectionContext[] collection() {
			return GetRuleContexts<CollectionContext>();
		}
		public CollectionContext collection(int i) {
			return GetRuleContext<CollectionContext>(i);
		}
		public OrganizationContext organization() {
			return GetRuleContext<OrganizationContext>(0);
		}
		public FileNameContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_fileName; } }
		public override void EnterRule(IParseTreeListener listener) {
			ISTEPListener typedListener = listener as ISTEPListener;
			if (typedListener != null) typedListener.EnterFileName(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			ISTEPListener typedListener = listener as ISTEPListener;
			if (typedListener != null) typedListener.ExitFileName(this);
		}
	}

	[RuleVersion(0)]
	public FileNameContext fileName() {
		FileNameContext _localctx = new FileNameContext(Context, State);
		EnterRule(_localctx, 18, RULE_fileName);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 111; Match(FILE_NAME);
			State = 112; Match(T__0);
			State = 113; name();
			State = 114; Match(T__1);
			State = 115; timeStamp();
			State = 116; Match(T__1);
			State = 119;
			ErrorHandler.Sync(this);
			switch (TokenStream.LA(1)) {
			case AnyString:
				{
				State = 117; author();
				}
				break;
			case T__0:
			case T__3:
				{
				State = 118; collection();
				}
				break;
			default:
				throw new NoViableAltException(this);
			}
			State = 121; Match(T__1);
			State = 124;
			ErrorHandler.Sync(this);
			switch (TokenStream.LA(1)) {
			case AnyString:
				{
				State = 122; organization();
				}
				break;
			case T__0:
			case T__3:
				{
				State = 123; collection();
				}
				break;
			default:
				throw new NoViableAltException(this);
			}
			State = 126; Match(T__1);
			State = 127; preprocessor_version();
			State = 128; Match(T__1);
			State = 129; originating_system();
			State = 130; Match(T__1);
			State = 131; authorisation();
			State = 132; Match(T__2);
			State = 133; Match(T__4);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class FilePathContext : ParserRuleContext {
		public ITerminalNode[] Letter() { return GetTokens(STEPParser.Letter); }
		public ITerminalNode Letter(int i) {
			return GetToken(STEPParser.Letter, i);
		}
		public FilePathContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_filePath; } }
		public override void EnterRule(IParseTreeListener listener) {
			ISTEPListener typedListener = listener as ISTEPListener;
			if (typedListener != null) typedListener.EnterFilePath(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			ISTEPListener typedListener = listener as ISTEPListener;
			if (typedListener != null) typedListener.ExitFilePath(this);
		}
	}

	[RuleVersion(0)]
	public FilePathContext filePath() {
		FilePathContext _localctx = new FilePathContext(Context, State);
		EnterRule(_localctx, 20, RULE_filePath);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 135; Match(T__5);
			State = 139;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			while (_la==Letter) {
				{
				{
				State = 136; Match(Letter);
				}
				}
				State = 141;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
			}
			State = 142; Match(T__6);
			State = 146;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			while (_la==Letter) {
				{
				{
				State = 143; Match(Letter);
				}
				}
				State = 148;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
			}
			State = 149; Match(T__5);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class FileSchemaContext : ParserRuleContext {
		public ITerminalNode FILE_SCHEMA() { return GetToken(STEPParser.FILE_SCHEMA, 0); }
		public ITerminalNode AnyString() { return GetToken(STEPParser.AnyString, 0); }
		public FileSchemaContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_fileSchema; } }
		public override void EnterRule(IParseTreeListener listener) {
			ISTEPListener typedListener = listener as ISTEPListener;
			if (typedListener != null) typedListener.EnterFileSchema(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			ISTEPListener typedListener = listener as ISTEPListener;
			if (typedListener != null) typedListener.ExitFileSchema(this);
		}
	}

	[RuleVersion(0)]
	public FileSchemaContext fileSchema() {
		FileSchemaContext _localctx = new FileSchemaContext(Context, State);
		EnterRule(_localctx, 22, RULE_fileSchema);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 151; Match(FILE_SCHEMA);
			State = 152; Match(T__0);
			State = 153; Match(T__0);
			State = 154; Match(AnyString);
			State = 155; Match(T__2);
			State = 156; Match(T__2);
			State = 157; Match(T__4);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class HeaderContext : ParserRuleContext {
		public ITerminalNode HEADER() { return GetToken(STEPParser.HEADER, 0); }
		public FileDescriptionContext fileDescription() {
			return GetRuleContext<FileDescriptionContext>(0);
		}
		public FileNameContext fileName() {
			return GetRuleContext<FileNameContext>(0);
		}
		public FileSchemaContext fileSchema() {
			return GetRuleContext<FileSchemaContext>(0);
		}
		public ITerminalNode ENDSEC() { return GetToken(STEPParser.ENDSEC, 0); }
		public HeaderContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_header; } }
		public override void EnterRule(IParseTreeListener listener) {
			ISTEPListener typedListener = listener as ISTEPListener;
			if (typedListener != null) typedListener.EnterHeader(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			ISTEPListener typedListener = listener as ISTEPListener;
			if (typedListener != null) typedListener.ExitHeader(this);
		}
	}

	[RuleVersion(0)]
	public HeaderContext header() {
		HeaderContext _localctx = new HeaderContext(Context, State);
		EnterRule(_localctx, 24, RULE_header);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 159; Match(HEADER);
			State = 160; Match(T__4);
			State = 161; fileDescription();
			State = 162; fileName();
			State = 163; fileSchema();
			State = 164; Match(ENDSEC);
			State = 165; Match(T__4);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class ImplementationContext : ParserRuleContext {
		public ITerminalNode AnyString() { return GetToken(STEPParser.AnyString, 0); }
		public ImplementationContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_implementation; } }
		public override void EnterRule(IParseTreeListener listener) {
			ISTEPListener typedListener = listener as ISTEPListener;
			if (typedListener != null) typedListener.EnterImplementation(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			ISTEPListener typedListener = listener as ISTEPListener;
			if (typedListener != null) typedListener.ExitImplementation(this);
		}
	}

	[RuleVersion(0)]
	public ImplementationContext implementation() {
		ImplementationContext _localctx = new ImplementationContext(Context, State);
		EnterRule(_localctx, 26, RULE_implementation);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 167; Match(AnyString);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class InstanceContext : ParserRuleContext {
		public ITerminalNode Id() { return GetToken(STEPParser.Id, 0); }
		public ConstructorContext constructor() {
			return GetRuleContext<ConstructorContext>(0);
		}
		public InstanceContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_instance; } }
		public override void EnterRule(IParseTreeListener listener) {
			ISTEPListener typedListener = listener as ISTEPListener;
			if (typedListener != null) typedListener.EnterInstance(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			ISTEPListener typedListener = listener as ISTEPListener;
			if (typedListener != null) typedListener.ExitInstance(this);
		}
	}

	[RuleVersion(0)]
	public InstanceContext instance() {
		InstanceContext _localctx = new InstanceContext(Context, State);
		EnterRule(_localctx, 28, RULE_instance);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 169; Match(Id);
			State = 170; Match(T__7);
			State = 171; constructor();
			State = 172; Match(T__4);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class NameContext : ParserRuleContext {
		public ITerminalNode AnyString() { return GetToken(STEPParser.AnyString, 0); }
		public FilePathContext filePath() {
			return GetRuleContext<FilePathContext>(0);
		}
		public NameContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_name; } }
		public override void EnterRule(IParseTreeListener listener) {
			ISTEPListener typedListener = listener as ISTEPListener;
			if (typedListener != null) typedListener.EnterName(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			ISTEPListener typedListener = listener as ISTEPListener;
			if (typedListener != null) typedListener.ExitName(this);
		}
	}

	[RuleVersion(0)]
	public NameContext name() {
		NameContext _localctx = new NameContext(Context, State);
		EnterRule(_localctx, 30, RULE_name);
		try {
			State = 176;
			ErrorHandler.Sync(this);
			switch (TokenStream.LA(1)) {
			case AnyString:
				EnterOuterAlt(_localctx, 1);
				{
				State = 174; Match(AnyString);
				}
				break;
			case T__5:
				EnterOuterAlt(_localctx, 2);
				{
				State = 175; filePath();
				}
				break;
			default:
				throw new NoViableAltException(this);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Originating_systemContext : ParserRuleContext {
		public ITerminalNode AnyString() { return GetToken(STEPParser.AnyString, 0); }
		public Originating_systemContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_originating_system; } }
		public override void EnterRule(IParseTreeListener listener) {
			ISTEPListener typedListener = listener as ISTEPListener;
			if (typedListener != null) typedListener.EnterOriginating_system(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			ISTEPListener typedListener = listener as ISTEPListener;
			if (typedListener != null) typedListener.ExitOriginating_system(this);
		}
	}

	[RuleVersion(0)]
	public Originating_systemContext originating_system() {
		Originating_systemContext _localctx = new Originating_systemContext(Context, State);
		EnterRule(_localctx, 32, RULE_originating_system);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 178; Match(AnyString);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class OrganizationContext : ParserRuleContext {
		public ITerminalNode AnyString() { return GetToken(STEPParser.AnyString, 0); }
		public OrganizationContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_organization; } }
		public override void EnterRule(IParseTreeListener listener) {
			ISTEPListener typedListener = listener as ISTEPListener;
			if (typedListener != null) typedListener.EnterOrganization(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			ISTEPListener typedListener = listener as ISTEPListener;
			if (typedListener != null) typedListener.ExitOrganization(this);
		}
	}

	[RuleVersion(0)]
	public OrganizationContext organization() {
		OrganizationContext _localctx = new OrganizationContext(Context, State);
		EnterRule(_localctx, 34, RULE_organization);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 180; Match(AnyString);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class ParameterContext : ParserRuleContext {
		public ConstructorContext constructor() {
			return GetRuleContext<ConstructorContext>(0);
		}
		public CollectionContext collection() {
			return GetRuleContext<CollectionContext>(0);
		}
		public ITerminalNode Undefined() { return GetToken(STEPParser.Undefined, 0); }
		public ITerminalNode StringLiteral() { return GetToken(STEPParser.StringLiteral, 0); }
		public ITerminalNode Derived() { return GetToken(STEPParser.Derived, 0); }
		public ITerminalNode Enum() { return GetToken(STEPParser.Enum, 0); }
		public ITerminalNode BoolLogical() { return GetToken(STEPParser.BoolLogical, 0); }
		public ITerminalNode RealLiteral() { return GetToken(STEPParser.RealLiteral, 0); }
		public ITerminalNode AnyString() { return GetToken(STEPParser.AnyString, 0); }
		public ITerminalNode Id() { return GetToken(STEPParser.Id, 0); }
		public ITerminalNode IntegerLiteral() { return GetToken(STEPParser.IntegerLiteral, 0); }
		public ParameterContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_parameter; } }
		public override void EnterRule(IParseTreeListener listener) {
			ISTEPListener typedListener = listener as ISTEPListener;
			if (typedListener != null) typedListener.EnterParameter(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			ISTEPListener typedListener = listener as ISTEPListener;
			if (typedListener != null) typedListener.ExitParameter(this);
		}
	}

	[RuleVersion(0)]
	public ParameterContext parameter() {
		ParameterContext _localctx = new ParameterContext(Context, State);
		EnterRule(_localctx, 36, RULE_parameter);
		try {
			State = 193;
			ErrorHandler.Sync(this);
			switch (TokenStream.LA(1)) {
			case TypeRef:
				EnterOuterAlt(_localctx, 1);
				{
				State = 182; constructor();
				}
				break;
			case T__0:
			case T__3:
				EnterOuterAlt(_localctx, 2);
				{
				State = 183; collection();
				}
				break;
			case Undefined:
				EnterOuterAlt(_localctx, 3);
				{
				State = 184; Match(Undefined);
				}
				break;
			case StringLiteral:
				EnterOuterAlt(_localctx, 4);
				{
				State = 185; Match(StringLiteral);
				}
				break;
			case Derived:
				EnterOuterAlt(_localctx, 5);
				{
				State = 186; Match(Derived);
				}
				break;
			case Enum:
				EnterOuterAlt(_localctx, 6);
				{
				State = 187; Match(Enum);
				}
				break;
			case BoolLogical:
				EnterOuterAlt(_localctx, 7);
				{
				State = 188; Match(BoolLogical);
				}
				break;
			case RealLiteral:
				EnterOuterAlt(_localctx, 8);
				{
				State = 189; Match(RealLiteral);
				}
				break;
			case AnyString:
				EnterOuterAlt(_localctx, 9);
				{
				State = 190; Match(AnyString);
				}
				break;
			case Id:
				EnterOuterAlt(_localctx, 10);
				{
				State = 191; Match(Id);
				}
				break;
			case IntegerLiteral:
				EnterOuterAlt(_localctx, 11);
				{
				State = 192; Match(IntegerLiteral);
				}
				break;
			default:
				throw new NoViableAltException(this);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Preprocessor_versionContext : ParserRuleContext {
		public ITerminalNode AnyString() { return GetToken(STEPParser.AnyString, 0); }
		public Preprocessor_versionContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_preprocessor_version; } }
		public override void EnterRule(IParseTreeListener listener) {
			ISTEPListener typedListener = listener as ISTEPListener;
			if (typedListener != null) typedListener.EnterPreprocessor_version(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			ISTEPListener typedListener = listener as ISTEPListener;
			if (typedListener != null) typedListener.ExitPreprocessor_version(this);
		}
	}

	[RuleVersion(0)]
	public Preprocessor_versionContext preprocessor_version() {
		Preprocessor_versionContext _localctx = new Preprocessor_versionContext(Context, State);
		EnterRule(_localctx, 38, RULE_preprocessor_version);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 195; Match(AnyString);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class TimeStampContext : ParserRuleContext {
		public ITerminalNode DateTime() { return GetToken(STEPParser.DateTime, 0); }
		public TimeStampContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_timeStamp; } }
		public override void EnterRule(IParseTreeListener listener) {
			ISTEPListener typedListener = listener as ISTEPListener;
			if (typedListener != null) typedListener.EnterTimeStamp(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			ISTEPListener typedListener = listener as ISTEPListener;
			if (typedListener != null) typedListener.ExitTimeStamp(this);
		}
	}

	[RuleVersion(0)]
	public TimeStampContext timeStamp() {
		TimeStampContext _localctx = new TimeStampContext(Context, State);
		EnterRule(_localctx, 40, RULE_timeStamp);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 197; Match(DateTime);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	private static char[] _serializedATN = {
		'\x3', '\x608B', '\xA72A', '\x8133', '\xB9ED', '\x417C', '\x3BE7', '\x7786', 
		'\x5964', '\x3', '#', '\xCA', '\x4', '\x2', '\t', '\x2', '\x4', '\x3', 
		'\t', '\x3', '\x4', '\x4', '\t', '\x4', '\x4', '\x5', '\t', '\x5', '\x4', 
		'\x6', '\t', '\x6', '\x4', '\a', '\t', '\a', '\x4', '\b', '\t', '\b', 
		'\x4', '\t', '\t', '\t', '\x4', '\n', '\t', '\n', '\x4', '\v', '\t', '\v', 
		'\x4', '\f', '\t', '\f', '\x4', '\r', '\t', '\r', '\x4', '\xE', '\t', 
		'\xE', '\x4', '\xF', '\t', '\xF', '\x4', '\x10', '\t', '\x10', '\x4', 
		'\x11', '\t', '\x11', '\x4', '\x12', '\t', '\x12', '\x4', '\x13', '\t', 
		'\x13', '\x4', '\x14', '\t', '\x14', '\x4', '\x15', '\t', '\x15', '\x4', 
		'\x16', '\t', '\x16', '\x3', '\x2', '\x3', '\x2', '\x3', '\x3', '\x3', 
		'\x3', '\x3', '\x4', '\x3', '\x4', '\x3', '\x4', '\x3', '\x4', '\a', '\x4', 
		'\x35', '\n', '\x4', '\f', '\x4', '\xE', '\x4', '\x38', '\v', '\x4', '\x3', 
		'\x4', '\x3', '\x4', '\x3', '\x4', '\x5', '\x4', '=', '\n', '\x4', '\x3', 
		'\x5', '\x3', '\x5', '\x3', '\x5', '\x3', '\x5', '\x3', '\x5', '\x3', 
		'\x5', '\x3', '\x5', '\x5', '\x5', '\x46', '\n', '\x5', '\x3', '\x6', 
		'\x3', '\x6', '\x3', '\x6', '\x5', '\x6', 'K', '\n', '\x6', '\x3', '\x6', 
		'\x3', '\x6', '\a', '\x6', 'O', '\n', '\x6', '\f', '\x6', '\xE', '\x6', 
		'R', '\v', '\x6', '\x3', '\x6', '\x3', '\x6', '\x3', '\a', '\x3', '\a', 
		'\x3', '\a', '\a', '\a', 'Y', '\n', '\a', '\f', '\a', '\xE', '\a', '\\', 
		'\v', '\a', '\x3', '\a', '\x3', '\a', '\x3', '\a', '\x3', '\b', '\x3', 
		'\b', '\x5', '\b', '\x63', '\n', '\b', '\x3', '\t', '\x3', '\t', '\x3', 
		'\t', '\x3', '\t', '\x3', '\t', '\x3', '\n', '\x3', '\n', '\x3', '\n', 
		'\x3', '\n', '\x3', '\n', '\x3', '\n', '\x3', '\n', '\x3', '\n', '\x3', 
		'\v', '\x3', '\v', '\x3', '\v', '\x3', '\v', '\x3', '\v', '\x3', '\v', 
		'\x3', '\v', '\x3', '\v', '\x5', '\v', 'z', '\n', '\v', '\x3', '\v', '\x3', 
		'\v', '\x3', '\v', '\x5', '\v', '\x7F', '\n', '\v', '\x3', '\v', '\x3', 
		'\v', '\x3', '\v', '\x3', '\v', '\x3', '\v', '\x3', '\v', '\x3', '\v', 
		'\x3', '\v', '\x3', '\v', '\x3', '\f', '\x3', '\f', '\a', '\f', '\x8C', 
		'\n', '\f', '\f', '\f', '\xE', '\f', '\x8F', '\v', '\f', '\x3', '\f', 
		'\x3', '\f', '\a', '\f', '\x93', '\n', '\f', '\f', '\f', '\xE', '\f', 
		'\x96', '\v', '\f', '\x3', '\f', '\x3', '\f', '\x3', '\r', '\x3', '\r', 
		'\x3', '\r', '\x3', '\r', '\x3', '\r', '\x3', '\r', '\x3', '\r', '\x3', 
		'\r', '\x3', '\xE', '\x3', '\xE', '\x3', '\xE', '\x3', '\xE', '\x3', '\xE', 
		'\x3', '\xE', '\x3', '\xE', '\x3', '\xE', '\x3', '\xF', '\x3', '\xF', 
		'\x3', '\x10', '\x3', '\x10', '\x3', '\x10', '\x3', '\x10', '\x3', '\x10', 
		'\x3', '\x11', '\x3', '\x11', '\x5', '\x11', '\xB3', '\n', '\x11', '\x3', 
		'\x12', '\x3', '\x12', '\x3', '\x13', '\x3', '\x13', '\x3', '\x14', '\x3', 
		'\x14', '\x3', '\x14', '\x3', '\x14', '\x3', '\x14', '\x3', '\x14', '\x3', 
		'\x14', '\x3', '\x14', '\x3', '\x14', '\x3', '\x14', '\x3', '\x14', '\x5', 
		'\x14', '\xC4', '\n', '\x14', '\x3', '\x15', '\x3', '\x15', '\x3', '\x16', 
		'\x3', '\x16', '\x3', '\x16', '\x2', '\x2', '\x17', '\x2', '\x4', '\x6', 
		'\b', '\n', '\f', '\xE', '\x10', '\x12', '\x14', '\x16', '\x18', '\x1A', 
		'\x1C', '\x1E', ' ', '\"', '$', '&', '(', '*', '\x2', '\x2', '\x2', '\xCF', 
		'\x2', ',', '\x3', '\x2', '\x2', '\x2', '\x4', '.', '\x3', '\x2', '\x2', 
		'\x2', '\x6', '<', '\x3', '\x2', '\x2', '\x2', '\b', '\x45', '\x3', '\x2', 
		'\x2', '\x2', '\n', 'G', '\x3', '\x2', '\x2', '\x2', '\f', 'U', '\x3', 
		'\x2', '\x2', '\x2', '\xE', '\x62', '\x3', '\x2', '\x2', '\x2', '\x10', 
		'\x64', '\x3', '\x2', '\x2', '\x2', '\x12', 'i', '\x3', '\x2', '\x2', 
		'\x2', '\x14', 'q', '\x3', '\x2', '\x2', '\x2', '\x16', '\x89', '\x3', 
		'\x2', '\x2', '\x2', '\x18', '\x99', '\x3', '\x2', '\x2', '\x2', '\x1A', 
		'\xA1', '\x3', '\x2', '\x2', '\x2', '\x1C', '\xA9', '\x3', '\x2', '\x2', 
		'\x2', '\x1E', '\xAB', '\x3', '\x2', '\x2', '\x2', ' ', '\xB2', '\x3', 
		'\x2', '\x2', '\x2', '\"', '\xB4', '\x3', '\x2', '\x2', '\x2', '$', '\xB6', 
		'\x3', '\x2', '\x2', '\x2', '&', '\xC3', '\x3', '\x2', '\x2', '\x2', '(', 
		'\xC5', '\x3', '\x2', '\x2', '\x2', '*', '\xC7', '\x3', '\x2', '\x2', 
		'\x2', ',', '-', '\a', ' ', '\x2', '\x2', '-', '\x3', '\x3', '\x2', '\x2', 
		'\x2', '.', '/', '\a', ' ', '\x2', '\x2', '/', '\x5', '\x3', '\x2', '\x2', 
		'\x2', '\x30', '\x31', '\a', '\x3', '\x2', '\x2', '\x31', '\x36', '\x5', 
		'\b', '\x5', '\x2', '\x32', '\x33', '\a', '\x4', '\x2', '\x2', '\x33', 
		'\x35', '\x5', '\b', '\x5', '\x2', '\x34', '\x32', '\x3', '\x2', '\x2', 
		'\x2', '\x35', '\x38', '\x3', '\x2', '\x2', '\x2', '\x36', '\x34', '\x3', 
		'\x2', '\x2', '\x2', '\x36', '\x37', '\x3', '\x2', '\x2', '\x2', '\x37', 
		'\x39', '\x3', '\x2', '\x2', '\x2', '\x38', '\x36', '\x3', '\x2', '\x2', 
		'\x2', '\x39', ':', '\a', '\x5', '\x2', '\x2', ':', '=', '\x3', '\x2', 
		'\x2', '\x2', ';', '=', '\a', '\x6', '\x2', '\x2', '<', '\x30', '\x3', 
		'\x2', '\x2', '\x2', '<', ';', '\x3', '\x2', '\x2', '\x2', '=', '\a', 
		'\x3', '\x2', '\x2', '\x2', '>', '\x46', '\a', '\x13', '\x2', '\x2', '?', 
		'\x46', '\a', '\v', '\x2', '\x2', '@', '\x46', '\a', '\x1D', '\x2', '\x2', 
		'\x41', '\x46', '\a', ' ', '\x2', '\x2', '\x42', '\x46', '\a', '\x1A', 
		'\x2', '\x2', '\x43', '\x46', '\x5', '\n', '\x6', '\x2', '\x44', '\x46', 
		'\a', '\x1F', '\x2', '\x2', '\x45', '>', '\x3', '\x2', '\x2', '\x2', '\x45', 
		'?', '\x3', '\x2', '\x2', '\x2', '\x45', '@', '\x3', '\x2', '\x2', '\x2', 
		'\x45', '\x41', '\x3', '\x2', '\x2', '\x2', '\x45', '\x42', '\x3', '\x2', 
		'\x2', '\x2', '\x45', '\x43', '\x3', '\x2', '\x2', '\x2', '\x45', '\x44', 
		'\x3', '\x2', '\x2', '\x2', '\x46', '\t', '\x3', '\x2', '\x2', '\x2', 
		'G', 'H', '\a', '\x1E', '\x2', '\x2', 'H', 'J', '\a', '\x3', '\x2', '\x2', 
		'I', 'K', '\x5', '&', '\x14', '\x2', 'J', 'I', '\x3', '\x2', '\x2', '\x2', 
		'J', 'K', '\x3', '\x2', '\x2', '\x2', 'K', 'P', '\x3', '\x2', '\x2', '\x2', 
		'L', 'M', '\a', '\x4', '\x2', '\x2', 'M', 'O', '\x5', '&', '\x14', '\x2', 
		'N', 'L', '\x3', '\x2', '\x2', '\x2', 'O', 'R', '\x3', '\x2', '\x2', '\x2', 
		'P', 'N', '\x3', '\x2', '\x2', '\x2', 'P', 'Q', '\x3', '\x2', '\x2', '\x2', 
		'Q', 'S', '\x3', '\x2', '\x2', '\x2', 'R', 'P', '\x3', '\x2', '\x2', '\x2', 
		'S', 'T', '\a', '\x5', '\x2', '\x2', 'T', '\v', '\x3', '\x2', '\x2', '\x2', 
		'U', 'V', '\a', '\x14', '\x2', '\x2', 'V', 'Z', '\a', '\a', '\x2', '\x2', 
		'W', 'Y', '\x5', '\x1E', '\x10', '\x2', 'X', 'W', '\x3', '\x2', '\x2', 
		'\x2', 'Y', '\\', '\x3', '\x2', '\x2', '\x2', 'Z', 'X', '\x3', '\x2', 
		'\x2', '\x2', 'Z', '[', '\x3', '\x2', '\x2', '\x2', '[', ']', '\x3', '\x2', 
		'\x2', '\x2', '\\', 'Z', '\x3', '\x2', '\x2', '\x2', ']', '^', '\a', '\x15', 
		'\x2', '\x2', '^', '_', '\a', '\a', '\x2', '\x2', '_', '\r', '\x3', '\x2', 
		'\x2', '\x2', '`', '\x63', '\a', ' ', '\x2', '\x2', '\x61', '\x63', '\x5', 
		'\x6', '\x4', '\x2', '\x62', '`', '\x3', '\x2', '\x2', '\x2', '\x62', 
		'\x61', '\x3', '\x2', '\x2', '\x2', '\x63', '\xF', '\x3', '\x2', '\x2', 
		'\x2', '\x64', '\x65', '\a', '\x1B', '\x2', '\x2', '\x65', '\x66', '\x5', 
		'\x1A', '\xE', '\x2', '\x66', 'g', '\x5', '\f', '\a', '\x2', 'g', 'h', 
		'\a', '\x1C', '\x2', '\x2', 'h', '\x11', '\x3', '\x2', '\x2', '\x2', 'i', 
		'j', '\a', '\x16', '\x2', '\x2', 'j', 'k', '\a', '\x3', '\x2', '\x2', 
		'k', 'l', '\x5', '\xE', '\b', '\x2', 'l', 'm', '\a', '\x4', '\x2', '\x2', 
		'm', 'n', '\x5', '\x1C', '\xF', '\x2', 'n', 'o', '\a', '\x5', '\x2', '\x2', 
		'o', 'p', '\a', '\a', '\x2', '\x2', 'p', '\x13', '\x3', '\x2', '\x2', 
		'\x2', 'q', 'r', '\a', '\x17', '\x2', '\x2', 'r', 's', '\a', '\x3', '\x2', 
		'\x2', 's', 't', '\x5', ' ', '\x11', '\x2', 't', 'u', '\a', '\x4', '\x2', 
		'\x2', 'u', 'v', '\x5', '*', '\x16', '\x2', 'v', 'y', '\a', '\x4', '\x2', 
		'\x2', 'w', 'z', '\x5', '\x2', '\x2', '\x2', 'x', 'z', '\x5', '\x6', '\x4', 
		'\x2', 'y', 'w', '\x3', '\x2', '\x2', '\x2', 'y', 'x', '\x3', '\x2', '\x2', 
		'\x2', 'z', '{', '\x3', '\x2', '\x2', '\x2', '{', '~', '\a', '\x4', '\x2', 
		'\x2', '|', '\x7F', '\x5', '$', '\x13', '\x2', '}', '\x7F', '\x5', '\x6', 
		'\x4', '\x2', '~', '|', '\x3', '\x2', '\x2', '\x2', '~', '}', '\x3', '\x2', 
		'\x2', '\x2', '\x7F', '\x80', '\x3', '\x2', '\x2', '\x2', '\x80', '\x81', 
		'\a', '\x4', '\x2', '\x2', '\x81', '\x82', '\x5', '(', '\x15', '\x2', 
		'\x82', '\x83', '\a', '\x4', '\x2', '\x2', '\x83', '\x84', '\x5', '\"', 
		'\x12', '\x2', '\x84', '\x85', '\a', '\x4', '\x2', '\x2', '\x85', '\x86', 
		'\x5', '\x4', '\x3', '\x2', '\x86', '\x87', '\a', '\x5', '\x2', '\x2', 
		'\x87', '\x88', '\a', '\a', '\x2', '\x2', '\x88', '\x15', '\x3', '\x2', 
		'\x2', '\x2', '\x89', '\x8D', '\a', '\b', '\x2', '\x2', '\x8A', '\x8C', 
		'\a', '\f', '\x2', '\x2', '\x8B', '\x8A', '\x3', '\x2', '\x2', '\x2', 
		'\x8C', '\x8F', '\x3', '\x2', '\x2', '\x2', '\x8D', '\x8B', '\x3', '\x2', 
		'\x2', '\x2', '\x8D', '\x8E', '\x3', '\x2', '\x2', '\x2', '\x8E', '\x90', 
		'\x3', '\x2', '\x2', '\x2', '\x8F', '\x8D', '\x3', '\x2', '\x2', '\x2', 
		'\x90', '\x94', '\a', '\t', '\x2', '\x2', '\x91', '\x93', '\a', '\f', 
		'\x2', '\x2', '\x92', '\x91', '\x3', '\x2', '\x2', '\x2', '\x93', '\x96', 
		'\x3', '\x2', '\x2', '\x2', '\x94', '\x92', '\x3', '\x2', '\x2', '\x2', 
		'\x94', '\x95', '\x3', '\x2', '\x2', '\x2', '\x95', '\x97', '\x3', '\x2', 
		'\x2', '\x2', '\x96', '\x94', '\x3', '\x2', '\x2', '\x2', '\x97', '\x98', 
		'\a', '\b', '\x2', '\x2', '\x98', '\x17', '\x3', '\x2', '\x2', '\x2', 
		'\x99', '\x9A', '\a', '\x18', '\x2', '\x2', '\x9A', '\x9B', '\a', '\x3', 
		'\x2', '\x2', '\x9B', '\x9C', '\a', '\x3', '\x2', '\x2', '\x9C', '\x9D', 
		'\a', ' ', '\x2', '\x2', '\x9D', '\x9E', '\a', '\x5', '\x2', '\x2', '\x9E', 
		'\x9F', '\a', '\x5', '\x2', '\x2', '\x9F', '\xA0', '\a', '\a', '\x2', 
		'\x2', '\xA0', '\x19', '\x3', '\x2', '\x2', '\x2', '\xA1', '\xA2', '\a', 
		'\x19', '\x2', '\x2', '\xA2', '\xA3', '\a', '\a', '\x2', '\x2', '\xA3', 
		'\xA4', '\x5', '\x12', '\n', '\x2', '\xA4', '\xA5', '\x5', '\x14', '\v', 
		'\x2', '\xA5', '\xA6', '\x5', '\x18', '\r', '\x2', '\xA6', '\xA7', '\a', 
		'\x15', '\x2', '\x2', '\xA7', '\xA8', '\a', '\a', '\x2', '\x2', '\xA8', 
		'\x1B', '\x3', '\x2', '\x2', '\x2', '\xA9', '\xAA', '\a', ' ', '\x2', 
		'\x2', '\xAA', '\x1D', '\x3', '\x2', '\x2', '\x2', '\xAB', '\xAC', '\a', 
		'\x1A', '\x2', '\x2', '\xAC', '\xAD', '\a', '\n', '\x2', '\x2', '\xAD', 
		'\xAE', '\x5', '\n', '\x6', '\x2', '\xAE', '\xAF', '\a', '\a', '\x2', 
		'\x2', '\xAF', '\x1F', '\x3', '\x2', '\x2', '\x2', '\xB0', '\xB3', '\a', 
		' ', '\x2', '\x2', '\xB1', '\xB3', '\x5', '\x16', '\f', '\x2', '\xB2', 
		'\xB0', '\x3', '\x2', '\x2', '\x2', '\xB2', '\xB1', '\x3', '\x2', '\x2', 
		'\x2', '\xB3', '!', '\x3', '\x2', '\x2', '\x2', '\xB4', '\xB5', '\a', 
		' ', '\x2', '\x2', '\xB5', '#', '\x3', '\x2', '\x2', '\x2', '\xB6', '\xB7', 
		'\a', ' ', '\x2', '\x2', '\xB7', '%', '\x3', '\x2', '\x2', '\x2', '\xB8', 
		'\xC4', '\x5', '\n', '\x6', '\x2', '\xB9', '\xC4', '\x5', '\x6', '\x4', 
		'\x2', '\xBA', '\xC4', '\a', '\x1F', '\x2', '\x2', '\xBB', '\xC4', '\a', 
		'\x1D', '\x2', '\x2', '\xBC', '\xC4', '\a', '\x10', '\x2', '\x2', '\xBD', 
		'\xC4', '\a', '\x12', '\x2', '\x2', '\xBE', '\xC4', '\a', '\x11', '\x2', 
		'\x2', '\xBF', '\xC4', '\a', '\x13', '\x2', '\x2', '\xC0', '\xC4', '\a', 
		' ', '\x2', '\x2', '\xC1', '\xC4', '\a', '\x1A', '\x2', '\x2', '\xC2', 
		'\xC4', '\a', '\v', '\x2', '\x2', '\xC3', '\xB8', '\x3', '\x2', '\x2', 
		'\x2', '\xC3', '\xB9', '\x3', '\x2', '\x2', '\x2', '\xC3', '\xBA', '\x3', 
		'\x2', '\x2', '\x2', '\xC3', '\xBB', '\x3', '\x2', '\x2', '\x2', '\xC3', 
		'\xBC', '\x3', '\x2', '\x2', '\x2', '\xC3', '\xBD', '\x3', '\x2', '\x2', 
		'\x2', '\xC3', '\xBE', '\x3', '\x2', '\x2', '\x2', '\xC3', '\xBF', '\x3', 
		'\x2', '\x2', '\x2', '\xC3', '\xC0', '\x3', '\x2', '\x2', '\x2', '\xC3', 
		'\xC1', '\x3', '\x2', '\x2', '\x2', '\xC3', '\xC2', '\x3', '\x2', '\x2', 
		'\x2', '\xC4', '\'', '\x3', '\x2', '\x2', '\x2', '\xC5', '\xC6', '\a', 
		' ', '\x2', '\x2', '\xC6', ')', '\x3', '\x2', '\x2', '\x2', '\xC7', '\xC8', 
		'\a', '\xE', '\x2', '\x2', '\xC8', '+', '\x3', '\x2', '\x2', '\x2', '\xF', 
		'\x36', '<', '\x45', 'J', 'P', 'Z', '\x62', 'y', '~', '\x8D', '\x94', 
		'\xB2', '\xC3',
	};

	public static readonly ATN _ATN =
		new ATNDeserializer().Deserialize(_serializedATN);


}
} // namespace STEP
