//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.13.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from C:/dev/Hypar/IFC-gen/grammar/STEP.g4 by ANTLR 4.13.1

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

namespace STEP {

using Antlr4.Runtime.Misc;
using IErrorNode = Antlr4.Runtime.Tree.IErrorNode;
using ITerminalNode = Antlr4.Runtime.Tree.ITerminalNode;
using IToken = Antlr4.Runtime.IToken;
using ParserRuleContext = Antlr4.Runtime.ParserRuleContext;

/// <summary>
/// This class provides an empty implementation of <see cref="ISTEPListener"/>,
/// which can be extended to create a listener which only needs to handle a subset
/// of the available methods.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.13.1")]
[System.Diagnostics.DebuggerNonUserCode]
[System.CLSCompliant(false)]
public partial class STEPBaseListener : ISTEPListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="STEPParser.author"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAuthor([NotNull] STEPParser.AuthorContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="STEPParser.author"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAuthor([NotNull] STEPParser.AuthorContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="STEPParser.authorisation"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAuthorisation([NotNull] STEPParser.AuthorisationContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="STEPParser.authorisation"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAuthorisation([NotNull] STEPParser.AuthorisationContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="STEPParser.collection"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterCollection([NotNull] STEPParser.CollectionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="STEPParser.collection"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitCollection([NotNull] STEPParser.CollectionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="STEPParser.collectionValue"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterCollectionValue([NotNull] STEPParser.CollectionValueContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="STEPParser.collectionValue"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitCollectionValue([NotNull] STEPParser.CollectionValueContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="STEPParser.constructor"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterConstructor([NotNull] STEPParser.ConstructorContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="STEPParser.constructor"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitConstructor([NotNull] STEPParser.ConstructorContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="STEPParser.data"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterData([NotNull] STEPParser.DataContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="STEPParser.data"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitData([NotNull] STEPParser.DataContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="STEPParser.description"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterDescription([NotNull] STEPParser.DescriptionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="STEPParser.description"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitDescription([NotNull] STEPParser.DescriptionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="STEPParser.file"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFile([NotNull] STEPParser.FileContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="STEPParser.file"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFile([NotNull] STEPParser.FileContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="STEPParser.fileDescription"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFileDescription([NotNull] STEPParser.FileDescriptionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="STEPParser.fileDescription"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFileDescription([NotNull] STEPParser.FileDescriptionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="STEPParser.fileName"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFileName([NotNull] STEPParser.FileNameContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="STEPParser.fileName"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFileName([NotNull] STEPParser.FileNameContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="STEPParser.filePath"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFilePath([NotNull] STEPParser.FilePathContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="STEPParser.filePath"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFilePath([NotNull] STEPParser.FilePathContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="STEPParser.fileSchema"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFileSchema([NotNull] STEPParser.FileSchemaContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="STEPParser.fileSchema"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFileSchema([NotNull] STEPParser.FileSchemaContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="STEPParser.header"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterHeader([NotNull] STEPParser.HeaderContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="STEPParser.header"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitHeader([NotNull] STEPParser.HeaderContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="STEPParser.implementation"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterImplementation([NotNull] STEPParser.ImplementationContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="STEPParser.implementation"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitImplementation([NotNull] STEPParser.ImplementationContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="STEPParser.instance"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterInstance([NotNull] STEPParser.InstanceContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="STEPParser.instance"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitInstance([NotNull] STEPParser.InstanceContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="STEPParser.name"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterName([NotNull] STEPParser.NameContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="STEPParser.name"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitName([NotNull] STEPParser.NameContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="STEPParser.originating_system"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterOriginating_system([NotNull] STEPParser.Originating_systemContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="STEPParser.originating_system"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitOriginating_system([NotNull] STEPParser.Originating_systemContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="STEPParser.organization"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterOrganization([NotNull] STEPParser.OrganizationContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="STEPParser.organization"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitOrganization([NotNull] STEPParser.OrganizationContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="STEPParser.parameter"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterParameter([NotNull] STEPParser.ParameterContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="STEPParser.parameter"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitParameter([NotNull] STEPParser.ParameterContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="STEPParser.preprocessor_version"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterPreprocessor_version([NotNull] STEPParser.Preprocessor_versionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="STEPParser.preprocessor_version"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitPreprocessor_version([NotNull] STEPParser.Preprocessor_versionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="STEPParser.timeStamp"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTimeStamp([NotNull] STEPParser.TimeStampContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="STEPParser.timeStamp"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTimeStamp([NotNull] STEPParser.TimeStampContext context) { }

	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void EnterEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void ExitEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitTerminal([NotNull] ITerminalNode node) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitErrorNode([NotNull] IErrorNode node) { }
}
} // namespace STEP
